apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: hello-py
    context: hello-py
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
    - service.yaml
